### ISSUE TITLE
cannot use import/export syntax?

### ISSUE THREAD

**Issue by hacker0limbo** [playcode/playcode#33]
Hello:

I was trying to test a little bit react code in playcode today, and found it seems like you actually can not import or export components between different files, some screenshots are listed below:

![Screen Shot 2020-02-17 at 6 26 19 pm](https://user-images.githubusercontent.com/36297538/74645505-0ef2a400-51b3-11ea-93da-57546d350a68.png)

![Screen Shot 2020-02-17 at 6 26 25 pm](https://user-images.githubusercontent.com/36297538/74645517-13b75800-51b3-11ea-9ae0-ab8e001a1bee.png)

As you can see, i installed the `react` and `react-dom` library and change the syntax to `jsx`, so here all i wanna do is simply import the `HelloMessage` component to the `index.js` file, but it didn't work.

It could be i am not using this editor correctly as well, so how do i handle this?

Cheers

**Comment by ianberdin** [comment]
Hi. Thank you for your issue.

Yes, in PlayCode for simplicity, we did a little differently. Use the global scope instead of import/export.
[Example](https://playcode.io/501618).

This seems strange at first, but in practice it saves time. And don't forget, you can change the order of files using drag & drop.

**Comment by hacker0limbo** [comment]
Thanks, this sloves my confusion!
